[project]
name = "hdr-converter"
version = "1.0.0"
description = "A simple Python tool that converts HDR images (.hdr and .exr) to RGBM format using OpenCV and OpenEXR"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python-headless>=4.13.0.92",
    "openexr-numpy>=0.0.8",
    "pillow>=12.1.1",
    "pyside6>=6.10.2",
    "qtawesome>=1.4.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pyinstaller>=6.16.0",
    "ruff>=0.15.18",
]
